fails:Executing break from within a block returns from the original invoking method even in case of chained calls
