critical:Kernel.catch can be nested
fails:Kernel.catch yields a new, unique object when called without arguments
