fails:Kernel.fail raises a RuntimeError
fails:Kernel.fail is a private method
